/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-prerelease-2.27.1-0-gd4f9be441 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-prerelease-2.27.1-0-gd4f9be441"
#endif
#define SDL_REVISION_NUMBER 0
