/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-prerelease-2.25.1-0-g78ea6af2c (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-prerelease-2.25.1-0-g78ea6af2c"
#endif
#define SDL_REVISION_NUMBER 0
