/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.26.4-0-g07d0f51fa (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.26.4-0-g07d0f51fa"
#endif
#define SDL_REVISION_NUMBER 0
