/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.28.1-0-g4761467b2 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.28.1-0-g4761467b2"
#endif
#define SDL_REVISION_NUMBER 0
