/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.26.0-0-g0bfeed061 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.26.0-0-g0bfeed061"
#endif
#define SDL_REVISION_NUMBER 0
