/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-prerelease-2.29.3-0-g4a62e1c0c (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-prerelease-2.29.3-0-g4a62e1c0c"
#endif
#define SDL_REVISION_NUMBER 0
