/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-prerelease-2.29.1-0-gcfc22ac7d (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-prerelease-2.29.1-0-gcfc22ac7d"
#endif
#define SDL_REVISION_NUMBER 0
